//! Raw FFI bindings to the Discord Social SDK's C API (`cdiscord.h`).
//!
//! Everything here is generated by `bindgen` and is entirely unsafe. Prefer the
//! safe wrapper in the `discord_social_sdk` crate; reach for this crate only for
//! surface the wrapper does not yet cover.
//!
//! # Conventions in the underlying C API
//!
//! - **Handles** are `struct { void* opaque; }`. Each has `_Init`, `_Drop` and
//!   usually `_Clone`. A handle must be initialised before use and dropped
//!   exactly once.
//! - **Strings** are [`Discord_String`] (`ptr` + `size`, *not* NUL-terminated).
//!   Strings returned from the SDK are owned by the caller and must be released
//!   with [`Discord_Free`] on their `ptr`.
//! - **Optionals** are expressed as `bool Getter(self, T* out)` — a `false`
//!   return means "absent" and `out` is untouched. Setters take `T*` where null
//!   means "clear".
//! - **Callbacks** always come as a `(callback, userDataFree, userData)` triple,
//!   which is exactly enough to carry a boxed Rust closure and free it.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(rustdoc::broken_intra_doc_links)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
